### ISSUE TITLE
Interlex ids request for methodsOntologies terms

### ISSUE THREAD

**Issue by MFSY** [OpenKnowledgeSpace/methodsOntology#48]
Provide a list of terms (in csv format) for which an interlex URIs are requested: 
- current term’s URI/CURIE, 
- the ontology within which the term is defined, 
- it’s labels, synonyms and abbreviations, 
- requested interlex curie, 
- boolean flag telling whether the term needs to be integrated within NIF or not ?

**Comment by MFSY** [comment]
Fixed. checkout [here](https://github.com/NeuroscienceKnowledgeSpace/methodsOntology/tree/master/to_be_integrated_in_NIF)

**Comment by tgbugs** [comment]
Perfect. Thank you. Will start on this next Monday. https://github.com/SciCrunch/NIF-Ontology/issues/64
